# Generated by Django 6.0.1 on 2026-02-04 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_contrato_imovel_id_alter_imovel_locador_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imovel',
            old_name='locador_id',
            new_name='locador',
        ),
    ]
