# Generated by Django 6.0.1 on 2026-02-02 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_usuario_email_alter_usuario_telefone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='imovel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='api.imovel'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='locador_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imoveis', to='api.usuario'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='status',
            field=models.CharField(choices=[('DISPONIVEL', 'Disponivel'), ('ALUGADO', 'Alugado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='contrato_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='api.contrato'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='status',
            field=models.BooleanField(),
        ),
    ]
